import {_electron as electron,expect,test} from '@playwright/test';
import {mkdir,mkdtemp,readFile,writeFile,access} from 'node:fs/promises';
import {createServer} from 'node:http';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import type {} from '../../apps/desktop/src/shared/api';

/** 真实TCP网页、Electron/Python、引用/SQLite/三格式；dialogs/DNS映射/固定Main明确替身。 */
test('V4-010采集与云取消、原文最终引用和三格式新文件独立保存',async()=>{
  test.setTimeout(180000);const root=path.resolve('artifacts/test-results/V4-010');await mkdir(root,{recursive:true});const work=await mkdtemp(path.join(root,'electron-'));
  const urls:string[]=[];const server=createServer((req,res)=>{urls.push(req.url??'');const content='合成记录对比：A观察值10，B观察值20，需要核对冲突。缺少长期测量。'+req.url;res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});res.end(content);});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('合成服务器不可用');
  const stats=path.join(work,'model-stats.json');const env={...process.env,ORVIA_DEV_DATA_DIR:path.join(work,'profile'),ORVIA_RESEARCH_PORT:String(address.port),ORVIA_RESEARCH_STATS:stats,ORVIA_RESEARCH_OUTPUT:work,ORVIA_RESEARCH_CONFIRM:'0',ORVIA_RESEARCH_SAVE:'0'};
  for(const key of ['ELECTRON_RUN_AS_NODE','DEEPSEEK_API_KEY','ZHIPU_API_KEY','MIMO_API_KEY','TAVILY_API_KEY','REDIS_PASSWORD'])delete env[key];
  const launch=()=>electron.launch({args:[path.resolve('tests/e2e/v4-research-launch.cjs')],env});let app=await launch();
  try{
    let page=await app.firstWindow();await expect(page.getByText('本地服务已连接',{exact:true})).toBeVisible();
    const made=await page.evaluate(()=>window.orvia.chatCreate({client_request_id:crypto.randomUUID(),title:'合成调研验收'}));if(!made.ok)throw Error(made.message);const cid=made.result.id;
    await page.getByRole('button',{name:'设置',exact:true}).click();let panel=page.getByLabel('调研与报告',{exact:true});await panel.getByLabel('调研所属会话',{exact:true}).selectOption(cid);
    await panel.getByLabel('调研问题',{exact:true}).fill('合成记录比较、冲突与缺口');await panel.getByLabel('准确公共网页URL',{exact:true}).fill('http://research.example/a\nhttp://research.example/a\nhttp://research.example/b');await panel.getByLabel('调研检索问题',{exact:true}).fill('合成待补充资料');await panel.getByLabel('调研准确站点约束',{exact:true}).fill('research.example');
    await panel.getByRole('button',{name:'创建准确调研计划',exact:true}).click();await panel.getByRole('button',{name:'原生批准准确调研采集',exact:true}).click();await expect(panel.getByText('已取消原生采集批准，未读取网页、搜索或调用模型。',{exact:true})).toBeVisible();expect(urls).toHaveLength(0);
    await app.evaluate(()=>{process.env.ORVIA_RESEARCH_CONFIRM='1';});
    const skill=await page.evaluate(id=>window.orvia.skillsRun({skill_id:'web-research',inputs:{query:'合成记录比较',urls:'http://research.example/a\nhttp://research.example/b'},conversation_id:id}),cid);if(!skill.ok||!skill.result.result)throw Error('Web Research没有实际准备计划');expect(skill.result.result.status).toBe('limited');const prepared=skill.result.result.steps[0].result?.task as {operation_id:string};expect(prepared.operation_id).toBeTruthy();expect(urls).toHaveLength(0);
    await panel.getByRole('button',{name:'刷新调研与回答事实',exact:true}).click();await panel.getByLabel('本会话调研历史',{exact:true}).selectOption(prepared.operation_id);await panel.getByRole('button',{name:'重新核对已保存采集计划',exact:true}).click();await panel.getByRole('button',{name:'原生批准准确调研采集',exact:true}).click();
    await expect(panel.getByLabel('调研事实',{exact:true})).toContainText('资料已采集');expect(urls).toEqual(['/a','/b']);await expect(panel.getByLabel('调研事实',{exact:true})).toContainText('检索轮次 0/2');
    await panel.getByLabel('调研模型阶段',{exact:true}).selectOption('batch');await panel.getByRole('button',{name:'准备准确调研发送预览',exact:true}).click();await expect(panel.getByLabel('调研完整发送输入',{exact:true})).toHaveValue(/合成记录/);
    await app.evaluate(()=>{process.env.ORVIA_RESEARCH_CONFIRM='0';});await panel.getByRole('button',{name:'原生批准此批调研模型发送',exact:true}).click();await expect(panel.getByText('已取消此批原生批准，未调用模型。',{exact:true})).toBeVisible();await expect(access(stats)).rejects.toThrow();
    await app.evaluate(()=>{process.env.ORVIA_RESEARCH_CONFIRM='1';});await panel.getByRole('button',{name:'准备准确调研发送预览',exact:true}).click();await panel.getByRole('button',{name:'原生批准此批调研模型发送',exact:true}).click();await expect(panel.getByLabel('调研事实',{exact:true})).toContainText('批摘要 1 · saved');
    await panel.getByLabel('调研模型阶段',{exact:true}).selectOption('final');await panel.getByRole('button',{name:'准备准确调研发送预览',exact:true}).click();const input=await panel.getByLabel('调研完整发送输入',{exact:true}).inputValue();expect(input).toContain('合成记录');expect(JSON.parse(input).fragments).toHaveLength(2);
    await panel.getByRole('button',{name:'原生批准此批调研模型发送',exact:true}).click();await expect(panel.getByLabel('模型综合回答',{exact:true})).toContainText('来源冲突');expect(JSON.parse(await readFile(stats,'utf8')).model_calls).toHaveLength(2);
    await panel.getByLabel('模型综合回答',{exact:true}).getByRole('button',{name:/http:\/\/research\.example\/a/}).first().click();await expect(panel.getByLabel('调研原文来源详情',{exact:true})).toHaveValue(/合成记录/);
    const savedResearch=await page.evaluate(id=>window.orvia.researchHistory({id}),cid);if(!savedResearch.ok)throw Error(savedResearch.message);const savedId=savedResearch.result.tasks.find(t=>t.final.state==='saved')?.final.message_id;if(!savedId)throw Error('缺少保存综合');const report=await page.evaluate(r=>window.orvia.skillsRun({skill_id:'report-build',inputs:{message_id:r.message_id,format:'docx',title:'合成简报预览'},conversation_id:r.id}),{id:cid,message_id:savedId});if(!report.ok||!report.result.result)throw Error('Report Build没有实际版式预览');expect(report.result.result.status).toBe('limited');expect(report.result.result.steps[0].result?.status).toBe('pending_save');expect(report.result.result.steps[0].result?.preview).toBeTruthy();
    await panel.getByRole('button',{name:'制作 Word／PPT／PDF 简报',exact:true}).click();const composer=panel.getByLabel('简报成品制作',{exact:true});await composer.getByLabel('简报标题',{exact:true}).fill('合成调研简报');await composer.getByRole('button',{name:'预览内容与版面',exact:true}).click();await composer.getByRole('button',{name:'选择新文件路径并确认保存',exact:true}).click();await expect(panel.getByText('已取消保存，未创建文件；如需保存请重新预览。',{exact:true})).toBeVisible();await expect(access(path.join(work,'合成调研简报.docx'))).rejects.toThrow();
    await app.evaluate(()=>{process.env.ORVIA_RESEARCH_SAVE='1';});
    for(const format of ['docx','pptx','pdf']){await composer.getByLabel('成品格式',{exact:true}).selectOption(format);await composer.getByRole('button',{name:'预览内容与版面',exact:true}).click();await composer.getByRole('button',{name:'选择新文件路径并确认保存',exact:true}).click();await expect(panel.getByText('成品已创建并读回核验。',{exact:true})).toBeVisible();await expect.poll(async()=>{try{await access(path.join(work,'合成调研简报.'+format));return true;}catch{return false;}}).toBe(true);}
    const history=await page.evaluate(id=>window.orvia.researchHistory({id}),cid);if(!history.ok)throw Error(history.message);const finished=history.result.tasks.find(t=>t.final.state==='saved');expect(finished?.publications).toHaveLength(3);if(!finished)throw Error('最终调研未保存');
    execFileSync(path.resolve('backend/.venv/Scripts/python.exe'),['-I','-X','utf8','-c',"import sys;from pathlib import Path;from docx import Document;from pptx import Presentation;import pypdfium2 as p;root=Path(sys.argv[1]);d=Document(root/'合成调研简报.docx');assert d.tables and 'browser:' in d.tables[0].rows[1].cells[1].text;s=Presentation(root/'合成调研简报.pptx');assert len(s.slides)>1;pdf=p.PdfDocument(root/'合成调研简报.pdf');assert len(pdf)>1;assert '合成调研简报' in pdf[0].get_textpage().get_text_bounded();pdf.close()",work]);
    await page.screenshot({path:path.join(work,'research-three-formats.png')});await app.close();app=await launch();page=await app.firstWindow();await expect(page.getByText('本地服务已连接',{exact:true})).toBeVisible();const restored=await page.evaluate(r=>window.orvia.researchStatus(r),{id:cid,operation_id:finished.operation_id});expect(restored.ok&&restored.result).toEqual(finished);expect(urls).toEqual(['/a','/b']);expect(JSON.parse(await readFile(stats,'utf8')).model_calls).toHaveLength(2);
    const replay=await page.evaluate(r=>window.orvia.researchGenerate(r),{id:cid,operation_id:finished.operation_id,stage:'final',revision:finished.final.revision!});expect(replay.ok).toBe(false);
    await writeFile(path.join(work,'acceptance.json'),JSON.stringify({module:'V4-010',actual:['TCP plaintext synthetic public page reads','Electron/preload/main/Python','immutable citation readback','SQLite/restart/no replay','DOCX/PPTX/PDF create/readback'],mock:['native dialogs','test-only public DNS socket mapping','two fixed Main completions'],realCloudCalls:0,webRequests:urls,formats:finished.publications,unverified:['manual native dialogs','production Internet/Tavily','real model semantic correctness']},null,2));
  }finally{await app.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
