import {_electron as electron,expect,test} from '@playwright/test';
import {mkdir,mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {createServer,type ServerResponse} from 'node:http';
import path from 'node:path';
import type {} from '../../apps/desktop/src/shared/api';

/** 真TCP 503→503→200及目标原文、真实Electron/Python/SQLite重开；路由和固定模型明确替身。 */
test('V4-011安全读取三次同业务尝试、逐目标核验、只读账本和重启零重放',async()=>{
  test.setTimeout(120000);const root=path.resolve('artifacts/test-results/V4-011');await mkdir(root,{recursive:true});const work=await mkdtemp(path.join(root,'electron-'));
  const requests:{path:string;status:number}[]=[];let three=0,second:ServerResponse|undefined,researchHeld:ServerResponse|undefined;
  const server=createServer((req,res)=>{const route=req.url??'';if(route==='/retry-three'&&++three<=2){requests.push({path:route,status:503});res.writeHead(503,{'Content-Type':'text/plain; charset=utf-8','Retry-After':'0'});res.end('合成暂时不可用');return;}
    requests.push({path:route,status:200});if(route==='/goal-two'){second=res;return;}if(route==='/research-cancel'){researchHeld=res;return;}res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});res.end('合成独立目标原文，允许逐项目标事实核验。'+route);});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('合成服务器不可用');
  const stats=path.join(work,'model-stats.json'),profile=path.join(work,'profile');const env={...process.env,ORVIA_DEV_DATA_DIR:profile,ORVIA_RETRY_PORT:String(address.port),ORVIA_RETRY_STATS:stats};
  for(const key of ['ELECTRON_RUN_AS_NODE','DEEPSEEK_API_KEY','ZHIPU_API_KEY','MIMO_API_KEY','TAVILY_API_KEY','REDIS_PASSWORD'])delete env[key];
  const launch=()=>electron.launch({args:[path.resolve('tests/e2e/v4-retry-launch.cjs'),`--user-data-dir=${profile}`],env});let app=await launch();
  try{
    let page=await app.firstWindow();await expect(page.getByText('本地服务已连接',{exact:true})).toBeVisible();
    const made=await page.evaluate(()=>window.orvia.chatCreate({client_request_id:crypto.randomUUID(),title:'合成安全读取验收'}));if(!made.ok)throw Error(made.message);const cid=made.result.id;
    const read=await page.evaluate(id=>window.orvia.chatBrowserRead({id,request_id:crypto.randomUUID(),url:'http://research.example/retry-three',mode:'http'}),cid);if(!read.ok)throw Error(read.message);
    expect(requests).toEqual([{path:'/retry-three',status:503},{path:'/retry-three',status:503},{path:'/retry-three',status:200}]);
    const before=await page.evaluate(id=>window.orvia.retryHistory({id}),cid);if(!before.ok)throw Error(before.message);const retried=before.result.runs.find(run=>run.tool==='browser.static_read'&&run.attempts.length===3);if(!retried)throw Error('缺少三次同业务读取事实');expect(retried.state).toBe('succeeded');expect(retried.attempts.map(item=>item.sequence)).toEqual([1,2,3]);expect(retried.attempts.map(item=>item.state)).toEqual(['failed','failed','succeeded']);expect(retried.attempts.map(item=>item.reason)).toEqual(['http_503','http_503','success']);expect(retried.attempts.slice(0,2).every(item=>item.delay_seconds<=0.5)).toBe(true);expect(JSON.stringify(before.result)).not.toContain('http://research.example');
    const other=await page.evaluate(()=>window.orvia.chatCreate({client_request_id:crypto.randomUUID(),title:'合成另一会话'}));if(!other.ok)throw Error(other.message);const otherHistory=await page.evaluate(id=>window.orvia.retryHistory({id}),other.result.id);if(!otherHistory.ok)throw Error(otherHistory.message);expect(otherHistory.result.runs).toEqual([]);
    await page.reload();await page.getByRole('button',{name:'合成安全读取验收',exact:true}).click();await page.getByRole('button',{name:'设置',exact:true}).click();let panel=page.getByLabel('安全读取重试记录',{exact:true});await panel.getByLabel('重试记录所属会话',{exact:true}).selectOption(cid);await panel.getByRole('button',{name:'刷新安全读取重试记录',exact:true}).click();const record=panel.getByLabel('安全读取重试事实',{exact:true}).filter({hasText:retried.business_id});await expect(record).toContainText('尝试 3/3');await record.getByText('同一准确请求的尝试序号、时间和原因',{exact:true}).click();await expect(record.getByLabel('读取尝试 3',{exact:true})).toContainText('收到成功结果');await expect(record.getByLabel('读取尝试 1',{exact:true})).toContainText('远端暂时不可用');await expect(record).toContainText('读取尝试已结束，不代表全任务完成');await record.getByLabel('读取尝试 3',{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(work,'retry-three-attempts.png')});
    await page.getByRole('button',{name:'关闭设置',exact:true}).click();await page.getByLabel('输入需求').fill('读取 http://research.example/goal-one；读取 http://research.example/goal-two');await page.getByLabel('输入需求').press('Enter');
    await expect.poll(()=>Boolean(second)).toBe(true);
    const control=await page.evaluate(async id=>{const started=performance.now();const reply=await window.orvia.retryHistory({id});return{elapsed:performance.now()-started,reply};},cid);expect(control.elapsed).toBeLessThan(3000);if(!control.reply.ok)throw Error(control.reply.message);expect(control.reply.result.runs.some(run=>run.tool==='browser.static_read'&&run.state==='running'&&run.attempts.some(attempt=>attempt.state==='running'))).toBe(true);expect(second).toBeTruthy();
    const partial=await page.evaluate(id=>window.orvia.chatGet({id}),cid);if(!partial.ok)throw Error(partial.message);expect(partial.result.task_progress?.steps.map(step=>step.status)).toEqual(['completed','running']);expect(partial.result.task_progress?.state).not.toBe('completed');
    // 只读历史打开会话读取进行中SQLite投影，不重放请求，也不重新加载整个应用。
    await page.getByRole('button',{name:'合成安全读取验收',exact:true}).click();const progress=page.getByLabel('完整目标进度',{exact:true});await expect(progress).toContainText('goal-one');await expect(progress).toContainText('goal-two');await expect(progress).toContainText('已完成：');await expect(page.locator('.topbar')).not.toContainText('已完成');await progress.screenshot({path:path.join(work,'two-goals-partial.png')});
    second!.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});second!.end('合成第二目标独立原文，真实保存以后才允许逐目标完成。');second=undefined;
    await expect.poll(async()=>{const r=await page.evaluate(id=>window.orvia.chatGet({id}),cid);return r.ok?r.result.task_progress?.state:null;}).toBe('completed');
    const final=await page.evaluate(id=>window.orvia.chatGet({id}),cid);if(!final.ok)throw Error(final.message);expect(final.result.task_progress?.steps.map(step=>step.status)).toEqual(['completed','completed']);expect(final.result.task_progress?.state).toBe('completed');expect(final.result.materials?.filter(item=>item.status==='ready')).toHaveLength(3);await page.getByRole('button',{name:'合成安全读取验收',exact:true}).click();await expect(page.locator('.topbar')).toContainText('已完成');await progress.getByText('本次目标进度',{exact:true}).click();await progress.screenshot({path:path.join(work,'two-goals-verified.png')});
    const planned=await page.evaluate(id=>window.orvia.researchCreate({id,question:'合成采集中止核验',urls:['http://research.example/research-cancel'],queries:[],sites:['research.example'],sources:[]}),cid);if(!planned.ok)throw Error(planned.message);const operation={id:cid,operation_id:planned.result.operation_id};
    const collecting=page.evaluate(r=>window.orvia.researchCollect(r),operation);await expect.poll(()=>Boolean(researchHeld)).toBe(true);
    const activeResearch=await page.evaluate(async r=>{const started=performance.now();const results=await Promise.all([window.orvia.researchStatus(r),window.orvia.researchHistory({id:r.id}),window.orvia.retryHistory({id:r.id})]);return{elapsed:performance.now()-started,results};},operation);expect(activeResearch.elapsed).toBeLessThan(3000);for(const result of activeResearch.results)expect(result.ok).toBe(true);const runningResearch=activeResearch.results[0];if(!runningResearch.ok)throw Error(runningResearch.message);expect(runningResearch.result.state).toBe('collecting');const activeRetry=activeResearch.results[2];if(!activeRetry.ok)throw Error(activeRetry.message);const cancelBusiness=activeRetry.result.runs.find(run=>run.tool==='browser.static_read'&&run.state==='running');if(!cancelBusiness)throw Error('研究运行中没有实际重试读取账本');
    const cancelled=await page.evaluate(r=>window.orvia.researchCancel(r),operation);if(!cancelled.ok)throw Error(cancelled.message);expect(cancelled.result.state).toBe('cancelled');const collectResult=await collecting;if(!collectResult.ok)throw Error(collectResult.message);expect(collectResult.result.result?.state).toBe('cancelled');const cancelHistory=await page.evaluate(id=>window.orvia.retryHistory({id}),cid);if(!cancelHistory.ok)throw Error(cancelHistory.message);expect(cancelHistory.result.runs.find(run=>run.business_id===cancelBusiness.business_id)?.state).toBe('cancelled');expect(requests.filter(item=>item.path==='/research-cancel')).toHaveLength(1);
    researchHeld!.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});researchHeld!.end('合成迟到正文不得变成已取消调研的成功来源。');researchHeld=undefined;const afterCancel=await page.evaluate(r=>window.orvia.researchStatus(r),operation);if(!afterCancel.ok)throw Error(afterCancel.message);expect(afterCancel.result.state).toBe('cancelled');expect(afterCancel.result.pages.every(item=>item.evidence_id===null)).toBe(true);expect(requests.filter(item=>item.path==='/research-cancel')).toHaveLength(1);
    // 未实现业务只验证显式接受限制，既不扫描已安装应用，也不把accepted伪称实际完成。
    await page.getByLabel('输入需求').fill('分析已安装应用及长期未使用的闲置应用；在聊天给出本次任务摘要');await page.getByLabel('输入需求').press('Enter');await expect(page.getByRole('button',{name:'接受此项未完成或受限范围，继续',exact:true})).toBeEnabled();await page.getByRole('button',{name:'接受此项未完成或受限范围，继续',exact:true}).click();
    await expect.poll(async()=>{const r=await page.evaluate(id=>window.orvia.chatGet({id}),cid);return r.ok?r.result.task_progress?.steps.map(step=>step.status).join(','):null;}).toBe('accepted,completed');await expect(page.getByRole('button',{name:'接受此项未完成或受限范围，继续',exact:true})).toHaveCount(0);
    const accepted=await page.evaluate(id=>window.orvia.chatGet({id}),cid);if(!accepted.ok)throw Error(accepted.message);expect(accepted.result.task_progress?.steps.map(step=>step.status)).toEqual(['accepted','completed']);expect(accepted.result.messages.some(message=>message.kind==='task_acceptance')).toBe(true);expect(accepted.result.messages.some(message=>message.kind==='task_summary')).toBe(true);const acceptedProgress=page.getByLabel('完整目标进度',{exact:true});await acceptedProgress.getByText('本次目标进度',{exact:true}).click();await expect(acceptedProgress).toContainText('接受限制不等于该目标已经完成');await expect(acceptedProgress).toContainText('已接受未执行或受限范围');await acceptedProgress.screenshot({path:path.join(work,'accepted-not-executed.png')});
    const saved=await page.evaluate(id=>window.orvia.retryHistory({id}),cid);if(!saved.ok)throw Error(saved.message);const sent=requests.slice();await app.close();app=await launch();page=await app.firstWindow();await expect(page.getByText('本地服务已连接',{exact:true})).toBeVisible();const restored=await page.evaluate(id=>window.orvia.retryHistory({id}),cid);expect(restored).toEqual(saved);expect(requests).toEqual(sent);await page.getByRole('button',{name:'设置',exact:true}).click();panel=page.getByLabel('安全读取重试记录',{exact:true});await panel.getByLabel('重试记录所属会话',{exact:true}).selectOption(cid);await panel.getByLabel('重试记录所属会话',{exact:true}).selectOption(cid);await expect(panel.getByRole('button',{name:'刷新安全读取重试记录',exact:true})).toBeEnabled();await panel.getByRole('button',{name:'刷新安全读取重试记录',exact:true}).click();await expect(panel).toContainText(retried.business_id);await expect(panel).toContainText('尝试 3/3');await panel.getByLabel('安全读取重试事实',{exact:true}).filter({hasText:retried.business_id}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(work,'retry-restart-history.png')});expect(requests).toEqual(sent);
    let modelCalls=0;try{modelCalls=JSON.parse(await readFile(stats,'utf8')).model_calls.length;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}expect(modelCalls).toBe(0);
    const acceptedRestored=await page.evaluate(id=>window.orvia.chatGet({id}),cid);if(!acceptedRestored.ok)throw Error(acceptedRestored.message);expect(acceptedRestored.result.task_progress?.steps.map(step=>step.status)).toEqual(['accepted','completed']);expect(acceptedRestored.result.messages.some(message=>message.kind==='task_acceptance')).toBe(true);expect(requests).toEqual(sent);
    await writeFile(path.join(work,'acceptance.json'),JSON.stringify({module:'V4-011',actual:['real TCP503/503/200','Electron/preload/main/Python/SQLite','same-business 3 attempts','retry.history control during held real TCP read','two independent original-evidence goals with partial completion gate','research status/history/retry history/cancel control during held real TCP','cancelled read ledger and late response rejected','explicit acceptance of unsupported scope with task_acceptance/task_summary IPC and restart','restart persisted ledger and zero network replay','cross-conversation isolation'],mock:['native dialogs','fixed public DNS socket mapping','fixed Main provider installed but unused'],realCloudCalls:0,modelCalls,requests,threeAttemptBusiness:retried,controlLatencyMilliseconds:control.elapsed,researchControlLatencyMilliseconds:activeResearch.elapsed,researchCancelled:afterCancel.result,partialStatuses:partial.result.task_progress?.steps.map(step=>step.status),verifiedStatuses:final.result.task_progress?.steps.map(step=>step.status),acceptedStatuses:acceptedRestored.result.task_progress?.steps.map(step=>step.status),unverified:['manual native dialogs','production Internet','cancel during backoff (covered by separate protocol tests)']},null,2));
  }finally{second?.end('合成测试清理');researchHeld?.end('合成研究测试清理');await app.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
