/** 错误码映射为固定中文，不展示供应商正文、路径或异常输入。 */
export function chatErrorMessage(code: string): string {
  const messages: Record<string, string> = {
    SKILL_PACKAGE:'Skill 包须为普通本地目录，只含有界 SKILL.md 与 workflow.json；不接受脚本或链接。',
    SKILL_SCHEMA:'Skill 输入输出声明含不支持的类型或约束，请检查 Orvia v1 契约。',
    SKILL_CONTRACT:'Skill 输入、声明或工具结果不符合契约，流程未完成。',
    SKILL_UNAVAILABLE:'Skill 或依赖尚未就绪，请查看工作流状态。',
    SKILL_CHANGED:'包、依赖版本或启用状态已变化，请重新审查并生成计划。',
    SKILL_VERSION:'更新 Skill 内容必须使用不同版本，并重新审查。',
    SKILL_DEPENDENCY:'Skill 依赖缺失、循环或组合超过预算，不能执行。',
    SKILL_LIMIT:'Skills 注册、输入或组合计划超过当前资源预算。',
    SKILL_PLAN:'计划已使用、失效或重启清除，请重新预览并批准。',
    SKILL_REVIEW:'导入审查已失效，请重新选择并确认。',
    SKILL_PERMISSION:'工作流计划与任务授权不匹配，未执行。',
    SKILL_BUILTIN:'导入包不能覆盖内置工作流。',
    SKILL_TOOL:'该工具不在工作流允许清单中。',
    STREAM_UNSUPPORTED:'固定Main未支持本次所需流式；请明确确认同模型非流式新请求，可能再次收费。',
    STREAM_INTERRUPTED:'流式回答中断；部分文本尚未完成引用校验，未自动重试或制作成品。',
    STREAM_INVALID:'固定模型增量格式无效，结果未通过校验；请查看已保存事实。',
    UNSUPPORTED_TASK:'当前尚不支持这项任务；没有执行或编造结果。',
    DELETE_BLOCKED:'此对话仍有运行中、待审批、结果不确定的任务，或尚未恢复的隔离文件。请先核对任务并处理，不能自动取消副作用。',
    DELETE_UNAVAILABLE:'本地私有资料清理未完成，删除尚未确认成功；请重新连接以完成已确认的清理。',
    SOURCE_REQUIRED:'这项任务需要当前会话有效资料或已保存的带引用回答。请添加或明确选择资料。',
    STEP_NOT_VERIFIED:'本步骤尚未满足原需求的真实核验条件，仍等待确认；请核对执行账本、准确目标与后续步骤。',
    MATERIAL_LIMIT:'本次有效资料最多3项、附件合计30 MiB；请先移除不需要的关联。历史引用仍保留。',
    OUTPUT_LIMIT:'本次输入、输出或附件超出预算；未继续扩大范围。',
    M18_ISOLATION_UNAVAILABLE: 'Windows 脚本隔离无法核验，已停止；不会退回普通进程执行。',
    M18_ISOLATION_INVALID: '隔离任务路径或运行时身份不符合要求，执行已停止。',
    M18_RUNTIME_UNAVAILABLE: '经校验的 Python 3.12 私有运行时不可用。',
    M18_AUTH_EXPIRED: '本次自动化授权已过期，请重新观察和预览。',
    M18_DESKTOP_UNAVAILABLE: '没有可授权的普通权限应用窗口。',
    DESKTOP_UNAVAILABLE: 'Windows UI Automation 暂不可用，不能回退盲坐标操作。',
    DESKTOP_STALE: '应用控件已变化，请重新观察和逐步审批。',
    DESKTOP_TARGET_CHANGED: '所选应用窗口或程序身份变化，授权已停止。',
    DESKTOP_DENIED: '目标控件或应用不在当前可核验的操作范围。',
    BROWSER_WRITE_UNAVAILABLE: '专用 Chromium 写会话不可用，请核对浏览器安装。',
    BROWSER_RUNTIME_UNAVAILABLE: '配套完整 Chromium 不可用，请安装可见浏览器运行时后重新授权。',
    BROWSER_OPEN_FAILED: '专用页面未成功加载，请核对准确网址；不会放宽网络或审批限制。',
    BROWSER_REDIRECT_REVIEW: 'HTTP 重定向未直接跟随，请明确授权最终 HTTPS 页面；提交后的外部结果需先人工核对。',
    BROWSER_PERMISSION_DENIED: '站点动作类别或 GET 写端点不符合本任务授权。',
    BROWSER_SESSION_INVALID: '专用浏览器会话已结束或不属于当前对话，请重新授权。',
    BROWSER_SESSION_EXPIRED: '专用浏览器会话已经结束，请重新授权站点。',
    BROWSER_OBSERVE_FAILED: '页面已变化或关闭，请重新观察。',
    PERMISSION_DENIED: '目录授权已失效，请重新选择目录。', permission_denied: '目录身份发生变化，请重新授权。',
    PATH_DENIED: '路径超出授权范围或包含不允许的链接。', path_denied: '路径超出授权范围或包含不允许的链接。',
    invalid_root: '请选择可访问的普通本地目录，不支持网络目录或链接。',
    path_unavailable: '路径不存在或无法访问，请刷新文件信息。',
    CONFLICT: '内容或目标发生冲突，请重新查看结果并生成计划。',
    INVALID_STATE: '任务状态已变化，当前操作不可用，请刷新会话。',
    STALE_PLAN: '计划已过期，请查看最新计划后再审批。',
    STALE_APPROVAL: '预览或计划版本已变化，请重新查看并确认。',
    SOURCE_UNAVAILABLE: '所选证据缺少可发送正文或提取失败，请改选版本。',
    ROOT_CHANGED: '目录身份已变化，请重新选择目录并生成计划。',
    SOURCE_CHANGED: '源文件在计划生成后发生变化，请重新生成计划。',
    RECOVERY_CONFLICT: '中断步骤无法安全核验，恢复已停止，不会重放不确定动作。',
    REQUEST_INTERRUPTED: '上次消息处理已中断，请检查现有结果后用新消息继续。',
    NOT_FOUND: '会话或任务不存在，请刷新会话列表。',
    MISSING_CREDENTIAL: '缺少固定模型凭据，请在设置中检查配置。',
    MODEL_UNAVAILABLE: '固定模型暂不可用；请核对本步骤已保存的事实，未自动重试。',
    BUDGET_EXCEEDED: '已达到本次任务预算，请停止并检查任务结果。',
    INVALID_PARAMS: '请求参数不符合当前业务接口。',
    STORAGE_BUSY: '本地数据库正在使用中，请稍后刷新；不要重复批准文件动作。',
    STORAGE_FULL: '本地磁盘空间不足，请释放空间后重连并核对任务状态。',
    STORAGE_UNAVAILABLE: '本地数据暂不可用，请检查磁盘与权限后重连；不会创建空白替代数据库。',
    SERVER_BUSY: '请求正在排队，请等待当前任务完成后刷新。',
    BACKEND_TIMEOUT: '本地服务响应超时，连接已停止。请重新连接并核对任务事实，不要重复审批。',
    BACKEND_DISCONNECTED: '本地后端已退出。请重新连接，重新授权目录后核对任务状态。',
    BACKEND_PROTOCOL: '本地通信协议异常，连接已停止。请重新连接；业务请求不会自动重放。',
    REQUEST_CANCELLED: '当前步骤已取消；已保存观察与事实保留，未批准步骤不会执行。',
    UNDO_CONFLICT: '文件已变化，撤销停止；请查看最新账本状态。',
    CODE_CHANGED: '项目文件在预览后变化，拒绝覆盖；请重新生成并核对差异。',
    CODE_PATH_DENIED: '生成路径不在授权项目和允许的文本文件范围。',
    CODE_LIMIT: '生成或上下文超出首批文件与大小预算。',
    CODE_FORMAT: '文件类型不属于所选语言/框架，或不是 UTF-8 文本。',
    CODE_ALREADY_APPLIED: '此代码文件已应用；不会重复写入。',
    CODE_ALREADY_GENERATED: '此生成请求已处理；请查看会话中保存的草稿。',
    INVALID_GENERATION: '固定 Computer 模型输出不符合受限草稿结构；未写入文件。',
    CLEANUP_UNAVAILABLE: '当前用户临时目录或同卷隔离区不可安全访问。',
    CLEANUP_DENIED: '文件不在清理白名单、过新、占用或不是普通文件。',
    CLEANUP_CHANGED: '临时文件在扫描后变化，已跳过；请重新扫描。',
    RESTORE_CONFLICT: '原位置已有文件，拒绝覆盖恢复。',
    RESTORE_CHANGED: '隔离文件身份或内容已变化，拒绝恢复。',
    RESTORE_EXPIRED: '受限恢复期限已过；隔离文件未自动永久删除。',
  };
  return messages[code] ?? '操作未完成，请刷新会话查看事实状态；任务步骤不会自动重放。';
}
